// const Restaurant = require('../../models/Restaurant')
// const seededUser = require('../allseeds/userSeed')
// const User = require('../../models/User')


const recipeSeed = (user) => {
  return [{
    name: 'Pappardelle with nduja, mascarpone and lemon',
    author: 'Michael',
    about: '',
    ingredients: ['Tagliatelle', 'Nduja', 'Mascarpone', 'Lemons (zest and juice)', 'Parsley', 'Parmesan', 'Olive oil'],
    method: ['Fry the nduja in the olive oil.', 'When the nduja has melted, add the lemon zest and juice, allow to infuse for a couple of minutes.', 'Add the mascarpone, reduce heat and stir', 'Once the sauce has thickened, add the cooked pasta and a tablespoon of its cooking water.', 'Serve topped with chopped parsley and parmesan'],
    image: 'https://i.imgur.com/rEM6L2U.jpg SameSite=None Secure',
    category: ['Pasta'],
    type: ['Dinner'],
    dietary: ['Spicy'],
    serves: '',
    complexity: 'Easy',
    time: '30mins or less!',
    user: user
  },
  {
    name: 'Sourdough Bread',
    author: 'Michael',
    about: '',
    ingredients: ['400g Strong White Bread Flour', '145g Rye Starter', '50g Rye Flour', '50g Wholemeal Flour', '12g Sea Salt', 'Olive Oil', 'Semolina (for dusting)'],
    method: ['Mix the flours and the starter.', 'Knead until the gluten develops.', 'Fold, then rest for 12 hours. Bake.'],
    image: 'https://imgur.com/PQaorBZ.jpg SameSite=None Secure',
    category: ['Baking'],
    type: ['Breakfast', 'Lunch', 'Dinner', 'Side'],
    dietary: [''],
    complexity: 'Bit more effort',
    serves: '',
    time: '3 days',
    user: user
  },
  {
    name: 'Ramen Noodles',
    author: 'Michael',
    about: '',
    ingredients: ['Eggs', 'Noodles', 'Soy Sauce', 'Spring Onions', 'Chicken Stock', 'Protein of your choice - e.g Chicken, Tofu', 'Vegetables of your choice'],
    method: ['Stick all the ingredients into a pot. Make sure they are cooked.', 'Delicious.'],
    image: 'https://i.imgur.com/1YKD8b1.jpg SameSite=None Secure',
    category: ['Asian', 'Soup'],
    type: ['Lunch', 'Dinner'],
    dietary: ['Vegetarian'],
    serves: '',
    complexity: 'Medium',
    time: 'One Hour',
    user: user
  },
  {
    name: 'Frying Pan Pizza',
    author: 'Pizza Pilgrims',
    about: 'Delicious Neopolitan Pizza. You can halve or quarter the quantities in this recipe as required',
    ingredients: ['1kg ‘00’ flour with a high gluten content', '2g fresh baker’s yeast', '600ml cold water', '30g table salt'],
    method: ['First, make the pizza base', 'Tip the flour onto your work service and make a well in the centre. Dissolve your yeast in the water and pour into the middle of the well a little at a time whilst using your hands to bring the walls of the flour in so that the water begins to thicken. Once you’ve reached the consistency of custard, add the salt and bring in the rest of the flour until it comes together as a dough. Knead for 10–15 minutes.', 'Cover and leave to rest for 10 minutes before kneading again quickly for 10 seconds (this helps to develop the flavour and the gluten).', 'Divide the dough into 200g balls and leave to rest overnight or for at least 8 hours (24 hours is optimal, 48 hours maximum) in a sealed container or a deep baking dish sprinkled with flour and covered in cling film. Remember to leave space for each of your dough balls because, as the gluten relaxes, they will spread out to take up twice the diameter that they do initially.', ' Scrape a dough ball out of its container using a spatula and as much flour as you need to ensure it doesn’t stick. The rounder the dough ball comes out, the rounder the final pizza base.', 'Put the dough ball onto a well-floured surface (honestly, if you are going to get serious about pizza making, get used to having flour play a large part in your life).', 'Using your fingertips, press out the dough ball firmly, starting at the centre and working out to the edge. Ensure you leave a centimetre around the rim of the pizza untouched.', 'Turn the dough ball over and repeat the pressing out process on the other side.', 'Using the palm of your hand, do one firm push in the centre of the dough ball to ensure the thickness of the base is consistent (not counting the raised edges).', 'Take the newly flattened dough ball on the back of your hands, ensuring the weight is on your knuckles and that your fingertips and nails are not going to poke a hole in the dough.', 'Using the back of your hands, stretch the dough out as far as you can without tearing it (now there’s a challenge). Turn the dough through 90 degrees and repeat this stretching. Do this a few times.', 'You should now have a disc of dough around 10 inches in diameter, consistently thin but with a slightly thicker rim. We are ready to cook.', 'Take the dough balls and press them out flat to make four 10 inch pizza bases using the tips of your fingers.', 'To make the tomato sauce, first crush the tomatoes by hand. This stops the seeds being whizzed up by the blender, which makes the sauce bitter. Add a pinch of salt, then blitz with a hand blender until you have a tomato sauce with a slightly rough texture.', 'Preheat the grill to its absolute highest setting.', 'Lay a pizza base flat in a dry frying pan (preferably non-stick) that has been on a high heat and is screaming hot.', 'Spread a thin layer of sauce with a ladle across the base, leaving a couple of centimetres round the edge for the crust. Add a pinch of Parmesan, basil leaves and a quarter of the mozzarella, in that order. Drizzle with olive oil.', 'Once the base of the pizza has browned (about 1–2 minutes), take the frying pan and place it on the highest shelf, under the grill.', 'Once the crust has taken on some colour (again about 1–2 minutes), the pizza is ready to go. Eat it fast (contrary to popular belief, pizza is not better cold the morning after!).', 'Start making the next one...'],
    image: 'https://i.imgur.com/Z4C6866.jpg SameSite=None Secure',
    category: ['Pizza', 'Italian', 'Baking'],
    type: ['Lunch', 'Dinner'],
    dietary: [''],
    serves: '8',
    complexity: 'Bit more effort',
    time: '1 hour (Plus 24 hours proving)',
    user: user
  },
  {
    name: 'Roast chicken with preserved lemon',
    author: 'Yotam Ottolenghi',
    about: 'The joy of a good roast is that the oven does all the work.',
    ingredients: ['70g unsalted butter, softened', '3 tbsp thyme leaves', '3 garlic cloves, peeled and crushed', '1 small preserved lemon, pips discarded, flesh and skin roughly chopped', 'Finely grated zest of 1 lemon, plus 1½ tbsp juice, to drizzle', 'Flaky sea salt and black pepper', '1.5kg free-range chicken'],
    method: ['Heat the oven to 190C/375F/gas mark 5. Put the butter, thyme, garlic, preserved lemon, lemon zest, half a teaspoon of salt and a good grind of pepper in a food processor. Blitz, then set aside while you tackle the bird.'],
    image: 'https://i.imgur.com/KzMBWqj.jpg',
    category: ['Chicken', 'Roast'],
    type: ['Lunch', 'Dinner'],
    dietary: [''],
    serves: '4',
    complexity: 'Easy',
    time: '90 minutes',
    user: user
  },
  {
    name: 'Chicken Tikka Masala',
    author: 'Felicity Cloake',
    about: 'A British staple. The ultimate spicy comfort food.',
    ingredients: ['4 boneless, skinless chicken thighs', '2 boneless, skinless chicken breasts', 'Juice of 2 lemons', '1 tsp salt', '150ml plain yoghurt', '1 tbsp pureed ginger', '1 tbsp crushed garlic', '1½ tsp ground cumin', '1 tbsp garam masala', '1 tbsp smoked sweet paprika', '2 tbsp ghee/clarified butter (or flavourless oil)', '2 small onions, chopped', '6 green cardamom pods', '1 black cardamom pod', '2cm cinnamon stick', '4 cloves', '2 tbsp pureed ginger (use a pestle and mortar)', '8 garlic cloves, crushed to a puree', '400g chopped tomatoes', '1 tbsp tomato puree', '2 small green chillies, split', '1 tsp sugar', '50ml whipping cream', '1 tsp paprika', '½ tsp fenugreek leaves, ground', '1 tsp garam masala', '1 tbsp lemon juice (optional)', 'Small handful of coriander leaves, to serve'],
    method: ['Cut the chicken into bite-sized chunks and stir in the lemon juice and salt. Leave to marinade for 30 minutes. Stir the remaining marinade ingredients together and add to the bowl. Stir well to coat, cover and chill overnight, then bring to room temperature before cooking.', 'To make the sauce, heat the ghee or other fat in a frying pan over a medium-high heat and add the onions. Fry until soft and golden brown, stirring regularly. Meanwhile, grind the seeds from the cardamom pods, the cinnamon stick and cloves to a smooth powder using a pestle and mortar.', 'Stir the pureed ginger and garlic into the onions and fry for a couple of minutes, stirring, then add the powdered spices and fry for a minute or so. Tip in the tomatoes and tomato puree plus 300ml water, bring to a simmer, turn the heat down to medium and cook until the oil starts to pool around the sides of the pan.', 'Meanwhile, heat your grill as high as it goes, and thread the chicken on to metal skewers, pushing the pieces well together. Put on a lined baking sheet as close to the grill as possible and grill for six to eight minutes on each side, until nicely charred at the edges.', 'Puree the sauce until smooth, then, once the chicken is done, return the pureed sauce to the pan on a medium heat. Stir any remaining marinade into the sauce, along with the chillies, sugar, cream and paprika – you can add more of the latter if necessary to give the sauce a deeper colour. Add the chicken, fenugreek and garam masala and cook for about five minutes, then taste for seasoning. Add more salt or sugar or the lemon juice if you like, then serve with chopped coriander.'],
    image: 'https://i.imgur.com/2ZHkLvw.jpg',
    category: ['Indian', 'Curry', 'Chicken', 'Asian'],
    type: ['Dinner'],
    dietary: [''],
    serves: '4',
    complexity: 'Medium',
    time: '1 hour (plus marinading overnight)',
    user: user
  },
  {
    name: 'Root Vegetable Cassoulet',
    author: 'Anna Jones',
    about: 'Crisp, fried butter beans, garlic, mustard, bay, oven-crisped bread and smoky roots, a one-pan hearty winter dinner to feed a crowd.',
    ingredients: ['Olive Oil', '400g root vegetables (carrots, swede, celeriac, potato, parsnip all work well), peeled and chopped into 2cm pieces', '1 leek, washed, trimmed, roughly sliced', '1 garlic clove, peeled and finely chopped', '1 red chilli, deseeded and finely chopped', '2 bay leaves', 'A pinch of smoked salt or sea salt and black pepper', '2 tbsp dijon mustard', '1 tbsp whole grain mustard', '400g tinned chopped tomatoes', '400g jar haricot or cannellini beans, drained, or 400g tinned, drained', '1 litre hot vegetable stock', 'A bunch of fresh thyme', '4 slices of sourdough bread'],
    method: ['Set the oven to 200C/400F/gas 6. Heat a glug of olive oil in an ovenproof pan over a medium heat. Throw in the root veg, leek, garlic, chilli and bay, and a pinch of the smoked salt and some pepper, then turn the heat down and cook for 10 minutes, or until the leeks are soft and sweet and the roots have begun to soften and brown.', 'Next, add the mustards, tinned tomatoes, beans and the stock. Simmer for 2 minutes, then take off the heat. Check the seasoning, and add a little more salt and pepper, if needed.', 'Scatter over the sprigs of thyme, then tear the slices of bread into chunks and push them into the gaps.', 'Drizzle the lot with olive oil and pop it into the oven for 30 minutes, or until the beans are crisp in places, the sauce is thick and has sweetened, and the bread is crisp and golden. Allow it to sit for a few minutes before piling on to plates with lemony green salad.'],
    image: 'https://i.imgur.com/b279dCm.jpg',
    category: ['Vegetable', 'Roast', 'One-pot'],
    type: ['Dinner'],
    dietary: ['Vegetarian', 'Vegan'],
    serves: '8',
    complexity: 'Easy',
    time: '1 hour',
    user: user
  },
  {
    name: 'Naan Bread',
    author: 'Felicity Cloake',
    about: 'Delicious Indian flatbreads',
    ingredients: ['1.5 tsp fast-action yeast', '1 tsp sugar', '150ml warm water', '300g strong white bread flour, plus extra to dust', '1 tsp salt', '5 tbsp natural yoghurt', '2 tbsp melted ghee or butter, plus extra to brush', 'A little vegetable oil, to grease', '1 tsp nigella (black onion), sesame or poppy seeds (optional)'],
    method: ['Put the yeast, sugar and two tablespoons of warm water in a bowl and stir well. Leave until it begins to froth.', 'Put the flour and salt into a large mixing bowl and whisk to combine. Stir the yoghurt into the yeast mixture, then make a well in the middle of the flour and pour it in, plus the melted ghee. Mix, then gradually stir in the water to make a soft, sticky mixture that is just firm enough to call a dough, but not at all dry. Tip out on a lightly floured surface and knead for about five minutes until smooth and a little less sticky, then put in a large, lightly oiled bowl and turn to coat. Cover and leave in a draught-free place (the airing cupboard, or an unlit oven) until doubled in size: roughly 90–120 minutes.', 'Tip the dough back out on to the lightly floured surface and knock the air out, then divide into eight balls (or six if you have a particularly large frying pan). Meanwhile, heat a non-stick frying pan over a very high heat for five minutes and put the oven on low. Prepare the melted ghee and any seeds to garnish.', 'Flatten one of the balls and prod or roll it into a flat circle, slightly thicker around the edge. Pick it up by the top to stretch it slightly into a teardrop shape, then put it in the hot pan. When it starts to bubble, turn it over and cook until the other side is browned in patches. Turn it back over and cook until there are no doughy bits remaining.', 'Brush with melted ghee and sprinkle with seeds, if using, and put in the oven to keep warm while you make the other breads.'],
    image: 'https://i.imgur.com/GWkt5ZO.jpg',
    category: ['Baking', 'Indian'],
    type: ['Side', 'Dinner'],
    dietary: ['Vegetarian'],
    serves: '6-8',
    complexity: 'Medium',
    time: '2 hours',
    user: user
  },

  {
    name: 'Fish Pie',
    author: 'Felicity Cloake',
    about: 'Rich, creamy comfort food on a plate',
    ingredients: ['1kg floury potatoes, eg Maris Piper or King Edwards', '50g butter', 'Splash of milk', '500ml fish stock', '100ml white wine', 'Small bunch of parsley, separated into leaves and stalks', '350g white fish fillets and / or salmon', '350g smoked white fish', '200g small peeled prawns', '50g butter', '50g plain flour', '200ml double cream', '2 anchovies, finely chopped', 'Handful of white breadcrumbs'],
    method: [' Preheat the oven to 180C. Peel the potatoes and cut into evenly sized chunks. Put in a large pan, cover with cold water, add a generous pinch of salt, and bring to the boil. Simmer for about 20 minutes, until tender. Drain, and allow to sit in the colander for a few minutes, then mash until smooth, and beat in the butter and a splash of milk. Season well and set aside.', 'Put the fish stock, wine and parsley stalks into a large pan, and bring to a simmer. Add the fish, and simmer for five of minutes, then lift out with a slotted spoon, remove the skins if any, and cut into large chunks. Discard the parsley stalks.', 'Melt the butter in a medium pan over a lowish heat, and then stir in the flour. Cook, stirring, for a couple of minutes, being careful not to let it brown. Gradually stir in the stock. Bring to the boil, then simmer for about 20 minutes.', 'Take the sauce off the heat, stir in the double cream, parsley leaves and anchovies and season. Add the fish and prawns and toss to coat.', ' Put the seafood and sauce into a baking dish and top with the mashed potato. Bake for 20 minutes, then sprinkle over the breadcrumbs and bake for a further 15, until the top is golden.'],
    image: 'https://i.imgur.com/3rTZPCO.jpg',
    category: ['Comfort Food', 'Seafood'],
    type: ['Dinner'],
    dietary: [''],
    serves: '4',
    complexity: 'Easy',
    time: '1.5 hours',
    user: user
  },

  {
    name: 'Sweet & Sour Chicken',
    author: 'John Torode',
    about: 'An authentic version of this classic Chinese takeaway dish, with natural sweetness and a warm chilli flavour to spice things up',
    ingredients: ['sunflower or vegetable oil, for frying', '100ml soda water, chilled', '140g self-raising flour', '25g cornflour', '4 skinless, boneless chicken breasts, cut into chunks', 'spring onions, finely shredded, to serve', '1 red pepper, deseeded and chopped into chunks', '3 red chillies, 1 cut into chunks, 2 halved and deseeded', '425g can pineapple chunks, drained and juice reserved', '4 star anisr', '50g tamarind paste', '100g caster sugar'],
    method: ['For the sauce, put the red pepper, chunks of chilli and pineapple juice in a pan and bring to the boil. Cover and cook for 10 mins, then purée in a food processor. Return to the pan with the pineapple chunks, chilli halves, star anise, tamarind, sugar and vinegar. Gently simmer for 20-30 mins until reduced and sticky. Keep warm, or reheat to serve.', 'Fill a large pan 1cm deep with oil and heat until shimmering. Whisk the soda water and 100ml cold water into the self-raising flour with a little salt. Tip the cornflour onto a plate, line a tray with kitchen paper and turn on the oven to low.', 'Stir the batter well. Dust the chicken with cornflour, then dip into the batter. One at a time, lower into the hot oil (about 5-6 every batch). Turn up the heat to keep the chicken frying, if needed, and cook for 5-6 mins, turning once. When cooked, drain on the tray, and keep warm in the oven. Repeat with the remaining chicken. Stack onto a plate with the warm sauce on the side, and scatter with shredded spring onions.'],
    image: 'https://i.imgur.com/SBF2vLM.jpg',
    category: ['Chinese', 'Asian', 'Chicken'],
    type: ['Dinner'],
    dietary: [''],
    serves: '4',
    complexity: 'Easy',
    time: '65 mins',
    user: user
  },

  {
    name: 'Keralan Fish Curry',
    author: 'Jamie Oliver',
    about: 'A beautifully creamy South-Indian curry, packed full of flavour and spice',
    ingredients: ['6 shallots', '4 cloves of garlic', '2.5 cm piece of ginger', '1 fresh green chilli', '750 g firm white fish , from sustainable sources', 'groundnut oil', '1 teaspoon mustard seeds', '20 curry leaves', '1 tablespoon chilli powder', '1 teaspoon turmeric', '1 x 400 g tin of coconut milk', '1 x 400 g tin of quality chopped tomatoes', 'a few sprigs of fresh coriander'],
    method: ['Peel and finely slice the shallots, garlic and ginger. Trim and finely slice the chilli. Cut the fish into chunks.', 'Heat a lug of groundnut oil in a large pan, add the mustard seeds and curry leaves and cook until the seeds start to pop.', 'Add the shallot, garlic, ginger and chilli, and cook on a medium heat for 5 minutes, or until softened.', 'Mix the chilli powder and turmeric together with a splash of water, and stir into the pan. Fry for 1 minute, then add the fish, coconut milk and tomatoes.', 'Season, bring to the boil, then simmer for 20 minutes, or until the fish is cooked and the sauce has reduced.', 'Pick, chop and scatter over the coriander leaves. Delicious served with basmati rice and warm naan bread.'],
    image: 'https://i.imgur.com/j5R5KPZ.png',
    category: ['Seafood', 'Indian', 'Curry'],
    type: ['Dinner'],
    dietary: [''],
    serves: '6-8',
    complexity: 'Easy',
    time: '40 minutes',
    user: user
  },

  {
    name: 'Nut Roast with Pistachios and Cranberries',
    author: 'Anna Jones',
    about: 'Nut roast is the vegetarian’s turkey, some crave something different but for others it’s not Christmas without it. A lover or a hater – this one is different, a flavour packed mushroom risotto base, sticky cranberries sit on the top a bit like a savoury upside down cake.',
    ingredients: ['A small handful of dried porcini', '2 tablespoons of olive oil', '2 red onions, peeled and finely chopped', '2 sticks of celery peeled and finely chopped', '2 cloves of garlic, peeled and finely chopped', '150g of risotto rice or pearl barley', '100ml of white wine', '500ml of good hot vegetable stock', '200g of mixed wild mushrooms', '100g of pistachios, toasted', '100g of almonds toasted', 'a handful of breadcrumbs from good bread', '125g of good cheddar cheese', '1 red chilli, finely chopped', 'the zest of 1 lemon', '2 eggs, beaten', '2 sprigs of each, sage rosemary, thyme, leaves picked and chopped', '200g of fresh cranberries', '2 tablespoons of light brown sugar'],
    method: ['First make the risotto base.', 'Soak the dried porcini in a little boiling water. Add the olive oil to a large pan, add the onion and celery and cook for 10 minutes on a low heat until soft and sweet. Add the garlic and cook for another minute or two. Turn up the heat and add the rice, cook the rice for a minute or so until you hear it snap, crackle and pop, then add the wine and stir until it has all bee absorbed.', 'Drain the mushrooms, sieve any grit from the liquor and add this to the risotto pan stirring until it is completely absorbed. Finely chop the soaked porcini and add these to the pan too.', 'Then add ladle by ladle of stock, stirring each one in until it has been completely absorbed this will take 20 minutes or so. Stir as much as you can this is what will make it creamy. Once the rice is al dente (when you break into a grain it should be almost cooked through but still have a little white fleck in the middle). Once you are happy put in a bowl to cool.', 'Heat the oven to 180C.', 'Fry the mushrooms in a little olive oil on a medium heat for 5-10 minutes until they are just starting to crisp and smell lovely and woody. Bash the nuts a little to break them down, you can do this in a food processor, you want coarse pieces not a powder.', 'Once the risotto is cooled add all the other ingredients apart form the cranberries and sugar and mix and mix well.', 'Put the sugar into a pan the cranberries and cook for a minute or two, then tip them into the bottom of the loaf tin and even out. Pile on the nut roast mixture and pack down with the back of a spoon.', 'Butter a 20cm loaf tin and line the bottom with greaseproof paper.', 'Cover with the whole thing with foil and bake for 45 minutes, remove the foil and cook for a further 15 minutes. Once it’s golden brown on top remove from the oven and leave to settle for 10 minutes. Lay you serving platter or board on top of the tin then cover your hand with a tea towel and courageously flip the whole lot over, use a knife tolosen the tin then carefully lift off. Serve with all the trimmings.'],
    image: 'https://i.imgur.com/LZaagTP.jpg',
    category: ['Vegetarian','Roast'],
    type: ['Dinner'],
    dietary: ['Vegetarian'],
    serves: '8-10',
    complexity: 'Bit more effort',
    time: '3 hours',
    user: user
  }

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    //}
  ]
}



module.exports = recipeSeed
