// const Restaurant = require('../../models/Restaurant')
// const seededUser = require('../allseeds/userSeed')
// const User = require('../../models/User')


const recipeSeed = (user) => {
  return [{
    name: 'Pappardelle with nduja, mascarpone and lemon',
    author: 'Michael',
    about: '',
    ingredients: ['Tagliatelle', 'Nduja', 'Mascarpone', 'Lemons (zest and juice)', 'Parsley', 'Parmesan', 'Olive oil'],
    method: ['Fry the nduja in the olive oil.', 'When the nduja has melted, add the lemon zest and juice, allow to infuse for a couple of minutes.', 'Add the mascarpone, reduce heat and stir', 'Once the sauce has thickened, add the cooked pasta and a tablespoon of its cooking water.', 'Serve topped with chopped parsley and parmesan'],
    image: 'https://i.imgur.com/rEM6L2U.jpg SameSite=None Secure',
    category: ['Pasta'],
    type: ['Dinner'],
    dietary: ['Spicy'],
    serves: '',
    complexity: 'Easy',
    time: '30mins or less!',
    user: user
  },
  {
    name: 'Sourdough Bread',
    author: 'Michael',
    about: '',
    ingredients: ['400g Strong White Bread Flour', '145g Rye Starter', '50g Rye Flour', '50g Wholemeal Flour', '12g Sea Salt', 'Olive Oil', 'Semolina (for dusting)'],
    method: ['Mix the flours and the starter.', 'Knead until the gluten develops.', 'Fold, then rest for 12 hours. Bake.'],
    image: 'https://imgur.com/PQaorBZ.jpg SameSite=None Secure',
    category: ['Baking'],
    type: ['Breakfast', 'Lunch', 'Dinner', 'Side'],
    dietary: [''],
    complexity: 'Bit more effort',
    serves: '',
    time: '3 days',
    user: user
  },
  {
    name: 'Ramen Noodles',
    author: 'Michael',
    about: '',
    ingredients: ['Eggs', 'Noodles', 'Soy Sauce', 'Spring Onions', 'Chicken Stock', 'Protein of your choice - e.g Chicken, Tofu', 'Vegetables of your choice'],
    method: ['Stick all the ingredients into a pot. Make sure they are cooked.', 'Delicious.'],
    image: 'https://i.imgur.com/1YKD8b1.jpg SameSite=None Secure',
    category: ['Asian', 'Soup'],
    type: ['Lunch', 'Dinner'],
    dietary: ['Vegetarian'],
    serves: '',
    complexity: 'Medium',
    time: 'One Hour',
    user: user
  },
  {
    name: 'Frying Pan Pizza',
    author: 'Pizza Pilgrims',
    about: 'Delicious Neopolitan Pizza. You can halve or quarter the quantities in this recipe as required',
    ingredients: ['1kg ‘00’ flour with a high gluten content', '2g fresh baker’s yeast', '600ml cold water', '30g table salt'],
    method: ['First, make the pizza base', 'Tip the flour onto your work service and make a well in the centre. Dissolve your yeast in the water and pour into the middle of the well a little at a time whilst using your hands to bring the walls of the flour in so that the water begins to thicken. Once you’ve reached the consistency of custard, add the salt and bring in the rest of the flour until it comes together as a dough. Knead for 10–15 minutes.', 'Cover and leave to rest for 10 minutes before kneading again quickly for 10 seconds (this helps to develop the flavour and the gluten).', 'Divide the dough into 200g balls and leave to rest overnight or for at least 8 hours (24 hours is optimal, 48 hours maximum) in a sealed container or a deep baking dish sprinkled with flour and covered in cling film. Remember to leave space for each of your dough balls because, as the gluten relaxes, they will spread out to take up twice the diameter that they do initially.', ' Scrape a dough ball out of its container using a spatula and as much flour as you need to ensure it doesn’t stick. The rounder the dough ball comes out, the rounder the final pizza base.', 'Put the dough ball onto a well-floured surface (honestly, if you are going to get serious about pizza making, get used to having flour play a large part in your life).', 'Using your fingertips, press out the dough ball firmly, starting at the centre and working out to the edge. Ensure you leave a centimetre around the rim of the pizza untouched.', 'Turn the dough ball over and repeat the pressing out process on the other side.', 'Using the palm of your hand, do one firm push in the centre of the dough ball to ensure the thickness of the base is consistent (not counting the raised edges).', 'Take the newly flattened dough ball on the back of your hands, ensuring the weight is on your knuckles and that your fingertips and nails are not going to poke a hole in the dough.', 'Using the back of your hands, stretch the dough out as far as you can without tearing it (now there’s a challenge). Turn the dough through 90 degrees and repeat this stretching. Do this a few times.', 'You should now have a disc of dough around 10 inches in diameter, consistently thin but with a slightly thicker rim. We are ready to cook.', 'Take the dough balls and press them out flat to make four 10 inch pizza bases using the tips of your fingers.', 'To make the tomato sauce, first crush the tomatoes by hand. This stops the seeds being whizzed up by the blender, which makes the sauce bitter. Add a pinch of salt, then blitz with a hand blender until you have a tomato sauce with a slightly rough texture.', 'Preheat the grill to its absolute highest setting.', 'Lay a pizza base flat in a dry frying pan (preferably non-stick) that has been on a high heat and is screaming hot.', 'Spread a thin layer of sauce with a ladle across the base, leaving a couple of centimetres round the edge for the crust. Add a pinch of Parmesan, basil leaves and a quarter of the mozzarella, in that order. Drizzle with olive oil.', 'Once the base of the pizza has browned (about 1–2 minutes), take the frying pan and place it on the highest shelf, under the grill.', 'Once the crust has taken on some colour (again about 1–2 minutes), the pizza is ready to go. Eat it fast (contrary to popular belief, pizza is not better cold the morning after!).', 'Start making the next one...'],
    image: 'https://i.imgur.com/Z4C6866.jpg SameSite=None Secure',
    category: ['Pizza', 'Italian', 'Baking'],
    type: ['Lunch', 'Dinner'],
    dietary: [''],
    serves: '8',
    complexity: 'Bit more effort',
    time: '1 hour (Plus 24 hours proving)',
    user: user
  },
  {
    name: 'Roast chicken with preserved lemon',
    author: 'Yotam Ottolenghi',
    about: 'The joy of a good roast is that the oven does all the work.',
    ingredients: ['70g unsalted butter, softened', '3 tbsp thyme leaves', '3 garlic cloves, peeled and crushed', '1 small preserved lemon, pips discarded, flesh and skin roughly chopped', 'Finely grated zest of 1 lemon, plus 1½ tbsp juice, to drizzle', 'Flaky sea salt and black pepper', '1.5kg free-range chicken'],
    method: ['Heat the oven to 190C/375F/gas mark 5. Put the butter, thyme, garlic, preserved lemon, lemon zest, half a teaspoon of salt and a good grind of pepper in a food processor. Blitz, then set aside while you tackle the bird.'],
    image: 'https://i.imgur.com/KzMBWqj.jpg',
    category: ['Chicken', 'Roast'],
    type: ['Lunch', 'Dinner'],
    dietary: [''],
    serves: '4',
    complexity: 'Easy',
    time: '90 minutes',
    user: user
  },
  {
    name: 'Chicken Tikka Masala',
    author: 'Felicity Cloake',
    about: 'A British staple. The ultimate spicy comfort food.',
    ingredients: ['4 boneless, skinless chicken thighs', '2 boneless, skinless chicken breasts', 'Juice of 2 lemons', '1 tsp salt', '150ml plain yoghurt', '1 tbsp pureed ginger', '1 tbsp crushed garlic', '1½ tsp ground cumin', '1 tbsp garam masala', '1 tbsp smoked sweet paprika', '2 tbsp ghee/clarified butter (or flavourless oil)', '2 small onions, chopped', '6 green cardamom pods', '1 black cardamom pod', '2cm cinnamon stick', '4 cloves', '2 tbsp pureed ginger (use a pestle and mortar)', '8 garlic cloves, crushed to a puree', '400g chopped tomatoes', '1 tbsp tomato puree', '2 small green chillies, split', '1 tsp sugar', '50ml whipping cream', '1 tsp paprika', '½ tsp fenugreek leaves, ground', '1 tsp garam masala', '1 tbsp lemon juice (optional)', 'Small handful of coriander leaves, to serve'],
    method: ['Cut the chicken into bite-sized chunks and stir in the lemon juice and salt. Leave to marinade for 30 minutes. Stir the remaining marinade ingredients together and add to the bowl. Stir well to coat, cover and chill overnight, then bring to room temperature before cooking.', 'To make the sauce, heat the ghee or other fat in a frying pan over a medium-high heat and add the onions. Fry until soft and golden brown, stirring regularly. Meanwhile, grind the seeds from the cardamom pods, the cinnamon stick and cloves to a smooth powder using a pestle and mortar.', 'Stir the pureed ginger and garlic into the onions and fry for a couple of minutes, stirring, then add the powdered spices and fry for a minute or so. Tip in the tomatoes and tomato puree plus 300ml water, bring to a simmer, turn the heat down to medium and cook until the oil starts to pool around the sides of the pan.', 'Meanwhile, heat your grill as high as it goes, and thread the chicken on to metal skewers, pushing the pieces well together. Put on a lined baking sheet as close to the grill as possible and grill for six to eight minutes on each side, until nicely charred at the edges.', 'Puree the sauce until smooth, then, once the chicken is done, return the pureed sauce to the pan on a medium heat. Stir any remaining marinade into the sauce, along with the chillies, sugar, cream and paprika – you can add more of the latter if necessary to give the sauce a deeper colour. Add the chicken, fenugreek and garam masala and cook for about five minutes, then taste for seasoning. Add more salt or sugar or the lemon juice if you like, then serve with chopped coriander.'],
    image: 'https://i.imgur.com/2ZHkLvw.jpg',
    category: ['Indian', 'Curry', 'Chicken', 'Asian'],
    type: ['Dinner'],
    dietary: [''],
    serves: '4',
    complexity: 'Medium',
    time: '1 hour (plus marinading overnight)',
    user: user
  },
  {
    name: 'Root Vegetable Cassoulet',
    author: 'Anna Jones',
    about: 'Crisp, fried butter beans, garlic, mustard, bay, oven-crisped bread and smoky roots, a one-pan hearty winter dinner to feed a crowd.',
    ingredients: ['Olive Oil', '400g root vegetables (carrots, swede, celeriac, potato, parsnip all work well), peeled and chopped into 2cm pieces', '1 leek, washed, trimmed, roughly sliced', '1 garlic clove, peeled and finely chopped', '1 red chilli, deseeded and finely chopped', '2 bay leaves', 'A pinch of smoked salt or sea salt and black pepper', '2 tbsp dijon mustard', '1 tbsp whole grain mustard', '400g tinned chopped tomatoes', '400g jar haricot or cannellini beans, drained, or 400g tinned, drained', '1 litre hot vegetable stock', 'A bunch of fresh thyme', '4 slices of sourdough bread'],
    method: ['Set the oven to 200C/400F/gas 6. Heat a glug of olive oil in an ovenproof pan over a medium heat. Throw in the root veg, leek, garlic, chilli and bay, and a pinch of the smoked salt and some pepper, then turn the heat down and cook for 10 minutes, or until the leeks are soft and sweet and the roots have begun to soften and brown.', 'Next, add the mustards, tinned tomatoes, beans and the stock. Simmer for 2 minutes, then take off the heat. Check the seasoning, and add a little more salt and pepper, if needed.', 'Scatter over the sprigs of thyme, then tear the slices of bread into chunks and push them into the gaps.', 'Drizzle the lot with olive oil and pop it into the oven for 30 minutes, or until the beans are crisp in places, the sauce is thick and has sweetened, and the bread is crisp and golden. Allow it to sit for a few minutes before piling on to plates with lemony green salad.'],
    image: 'https://i.imgur.com/b279dCm.jpg',
    category: ['Vegetable', 'Roast', 'One-pot', 'Comfort Food'],
    type: ['Dinner'],
    dietary: ['Vegetarian', 'Vegan'],
    serves: '8',
    complexity: 'Easy',
    time: '1 hour',
    user: user
  },
  {
    name: 'Naan Bread',
    author: 'Felicity Cloake',
    about: 'Delicious Indian flatbreads',
    ingredients: ['1.5 tsp fast-action yeast', '1 tsp sugar', '150ml warm water', '300g strong white bread flour, plus extra to dust', '1 tsp salt', '5 tbsp natural yoghurt', '2 tbsp melted ghee or butter, plus extra to brush', 'A little vegetable oil, to grease', '1 tsp nigella (black onion), sesame or poppy seeds (optional)'],
    method: ['Put the yeast, sugar and two tablespoons of warm water in a bowl and stir well. Leave until it begins to froth.', 'Put the flour and salt into a large mixing bowl and whisk to combine. Stir the yoghurt into the yeast mixture, then make a well in the middle of the flour and pour it in, plus the melted ghee. Mix, then gradually stir in the water to make a soft, sticky mixture that is just firm enough to call a dough, but not at all dry. Tip out on a lightly floured surface and knead for about five minutes until smooth and a little less sticky, then put in a large, lightly oiled bowl and turn to coat. Cover and leave in a draught-free place (the airing cupboard, or an unlit oven) until doubled in size: roughly 90–120 minutes.', 'Tip the dough back out on to the lightly floured surface and knock the air out, then divide into eight balls (or six if you have a particularly large frying pan). Meanwhile, heat a non-stick frying pan over a very high heat for five minutes and put the oven on low. Prepare the melted ghee and any seeds to garnish.', 'Flatten one of the balls and prod or roll it into a flat circle, slightly thicker around the edge. Pick it up by the top to stretch it slightly into a teardrop shape, then put it in the hot pan. When it starts to bubble, turn it over and cook until the other side is browned in patches. Turn it back over and cook until there are no doughy bits remaining.', 'Brush with melted ghee and sprinkle with seeds, if using, and put in the oven to keep warm while you make the other breads.'],
    image: 'https://i.imgur.com/GWkt5ZO.jpg',
    category: ['Baking', 'Indian'],
    type: ['Side', 'Dinner'],
    dietary: ['Vegetarian'],
    serves: '6-8',
    complexity: 'Medium',
    time: '2 hours',
    user: user
  },

  {
    name: 'Fish Pie',
    author: 'Felicity Cloake',
    about: 'Rich, creamy comfort food on a plate',
    ingredients: ['1kg floury potatoes, eg Maris Piper or King Edwards', '50g butter', 'Splash of milk', '500ml fish stock', '100ml white wine', 'Small bunch of parsley, separated into leaves and stalks', '350g white fish fillets and / or salmon', '350g smoked white fish', '200g small peeled prawns', '50g butter', '50g plain flour', '200ml double cream', '2 anchovies, finely chopped', 'Handful of white breadcrumbs'],
    method: [' Preheat the oven to 180C. Peel the potatoes and cut into evenly sized chunks. Put in a large pan, cover with cold water, add a generous pinch of salt, and bring to the boil. Simmer for about 20 minutes, until tender. Drain, and allow to sit in the colander for a few minutes, then mash until smooth, and beat in the butter and a splash of milk. Season well and set aside.', 'Put the fish stock, wine and parsley stalks into a large pan, and bring to a simmer. Add the fish, and simmer for five of minutes, then lift out with a slotted spoon, remove the skins if any, and cut into large chunks. Discard the parsley stalks.', 'Melt the butter in a medium pan over a lowish heat, and then stir in the flour. Cook, stirring, for a couple of minutes, being careful not to let it brown. Gradually stir in the stock. Bring to the boil, then simmer for about 20 minutes.', 'Take the sauce off the heat, stir in the double cream, parsley leaves and anchovies and season. Add the fish and prawns and toss to coat.', ' Put the seafood and sauce into a baking dish and top with the mashed potato. Bake for 20 minutes, then sprinkle over the breadcrumbs and bake for a further 15, until the top is golden.'],
    image: 'https://i.imgur.com/3rTZPCO.jpg',
    category: ['Comfort Food', 'Seafood'],
    type: ['Dinner'],
    dietary: [''],
    serves: '4',
    complexity: 'Easy',
    time: '1.5 hours',
    user: user
  },

  {
    name: 'Sweet & Sour Chicken',
    author: 'John Torode',
    about: 'An authentic version of this classic Chinese takeaway dish, with natural sweetness and a warm chilli flavour to spice things up',
    ingredients: ['sunflower or vegetable oil, for frying', '100ml soda water, chilled', '140g self-raising flour', '25g cornflour', '4 skinless, boneless chicken breasts, cut into chunks', 'spring onions, finely shredded, to serve', '1 red pepper, deseeded and chopped into chunks', '3 red chillies, 1 cut into chunks, 2 halved and deseeded', '425g can pineapple chunks, drained and juice reserved', '4 star anisr', '50g tamarind paste', '100g caster sugar'],
    method: ['For the sauce, put the red pepper, chunks of chilli and pineapple juice in a pan and bring to the boil. Cover and cook for 10 mins, then purée in a food processor. Return to the pan with the pineapple chunks, chilli halves, star anise, tamarind, sugar and vinegar. Gently simmer for 20-30 mins until reduced and sticky. Keep warm, or reheat to serve.', 'Fill a large pan 1cm deep with oil and heat until shimmering. Whisk the soda water and 100ml cold water into the self-raising flour with a little salt. Tip the cornflour onto a plate, line a tray with kitchen paper and turn on the oven to low.', 'Stir the batter well. Dust the chicken with cornflour, then dip into the batter. One at a time, lower into the hot oil (about 5-6 every batch). Turn up the heat to keep the chicken frying, if needed, and cook for 5-6 mins, turning once. When cooked, drain on the tray, and keep warm in the oven. Repeat with the remaining chicken. Stack onto a plate with the warm sauce on the side, and scatter with shredded spring onions.'],
    image: 'https://i.imgur.com/SBF2vLM.jpg',
    category: ['Chinese', 'Asian', 'Chicken'],
    type: ['Dinner'],
    dietary: [''],
    serves: '4',
    complexity: 'Easy',
    time: '65 mins',
    user: user
  },

  {
    name: 'Keralan Fish Curry',
    author: 'Jamie Oliver',
    about: 'A beautifully creamy South-Indian curry, packed full of flavour and spice',
    ingredients: ['6 shallots', '4 cloves of garlic', '2.5 cm piece of ginger', '1 fresh green chilli', '750 g firm white fish , from sustainable sources', 'groundnut oil', '1 teaspoon mustard seeds', '20 curry leaves', '1 tablespoon chilli powder', '1 teaspoon turmeric', '1 x 400 g tin of coconut milk', '1 x 400 g tin of quality chopped tomatoes', 'a few sprigs of fresh coriander'],
    method: ['Peel and finely slice the shallots, garlic and ginger. Trim and finely slice the chilli. Cut the fish into chunks.', 'Heat a lug of groundnut oil in a large pan, add the mustard seeds and curry leaves and cook until the seeds start to pop.', 'Add the shallot, garlic, ginger and chilli, and cook on a medium heat for 5 minutes, or until softened.', 'Mix the chilli powder and turmeric together with a splash of water, and stir into the pan. Fry for 1 minute, then add the fish, coconut milk and tomatoes.', 'Season, bring to the boil, then simmer for 20 minutes, or until the fish is cooked and the sauce has reduced.', 'Pick, chop and scatter over the coriander leaves. Delicious served with basmati rice and warm naan bread.'],
    image: 'https://i.imgur.com/j5R5KPZ.png',
    category: ['Seafood', 'Indian', 'Curry'],
    type: ['Dinner'],
    dietary: [''],
    serves: '6-8',
    complexity: 'Easy',
    time: '40 minutes',
    user: user
  },

  {
    name: 'Nut Roast with Pistachios and Cranberries',
    author: 'Anna Jones',
    about: 'Nut roast is the vegetarian’s turkey, some crave something different but for others it’s not Christmas without it. A lover or a hater – this one is different, a flavour packed mushroom risotto base, sticky cranberries sit on the top a bit like a savoury upside down cake.',
    ingredients: ['A small handful of dried porcini', '2 tablespoons of olive oil', '2 red onions, peeled and finely chopped', '2 sticks of celery peeled and finely chopped', '2 cloves of garlic, peeled and finely chopped', '150g of risotto rice or pearl barley', '100ml of white wine', '500ml of good hot vegetable stock', '200g of mixed wild mushrooms', '100g of pistachios, toasted', '100g of almonds toasted', 'a handful of breadcrumbs from good bread', '125g of good cheddar cheese', '1 red chilli, finely chopped', 'the zest of 1 lemon', '2 eggs, beaten', '2 sprigs of each, sage rosemary, thyme, leaves picked and chopped', '200g of fresh cranberries', '2 tablespoons of light brown sugar'],
    method: ['First make the risotto base.', 'Soak the dried porcini in a little boiling water. Add the olive oil to a large pan, add the onion and celery and cook for 10 minutes on a low heat until soft and sweet. Add the garlic and cook for another minute or two. Turn up the heat and add the rice, cook the rice for a minute or so until you hear it snap, crackle and pop, then add the wine and stir until it has all bee absorbed.', 'Drain the mushrooms, sieve any grit from the liquor and add this to the risotto pan stirring until it is completely absorbed. Finely chop the soaked porcini and add these to the pan too.', 'Then add ladle by ladle of stock, stirring each one in until it has been completely absorbed this will take 20 minutes or so. Stir as much as you can this is what will make it creamy. Once the rice is al dente (when you break into a grain it should be almost cooked through but still have a little white fleck in the middle). Once you are happy put in a bowl to cool.', 'Heat the oven to 180C.', 'Fry the mushrooms in a little olive oil on a medium heat for 5-10 minutes until they are just starting to crisp and smell lovely and woody. Bash the nuts a little to break them down, you can do this in a food processor, you want coarse pieces not a powder.', 'Once the risotto is cooled add all the other ingredients apart form the cranberries and sugar and mix and mix well.', 'Put the sugar into a pan the cranberries and cook for a minute or two, then tip them into the bottom of the loaf tin and even out. Pile on the nut roast mixture and pack down with the back of a spoon.', 'Butter a 20cm loaf tin and line the bottom with greaseproof paper.', 'Cover with the whole thing with foil and bake for 45 minutes, remove the foil and cook for a further 15 minutes. Once it’s golden brown on top remove from the oven and leave to settle for 10 minutes. Lay you serving platter or board on top of the tin then cover your hand with a tea towel and courageously flip the whole lot over, use a knife tolosen the tin then carefully lift off. Serve with all the trimmings.'],
    image: 'https://i.imgur.com/LZaagTP.jpg',
    category: ['Vegetarian', 'Roast'],
    type: ['Dinner'],
    dietary: ['Vegetarian'],
    serves: '8-10',
    complexity: 'Bit more effort',
    time: '3 hours',
    user: user
  },

  {
    name: 'Chicken & Leek Pie',
    author: 'The Hairy Bikers',
    about: 'Unleash this crowning glory upon your guests – a delicious chicken and ham pie, bubbling with homemade goodness.',
    ingredients: ['450ml/16fl oz chicken stock', '3 chicken breasts, skinned', '75g/3oz butter', '2 leeks, trimmed and cut into 1cm/½in slices', '2 garlic cloves, crushed', '50g/2oz plain flour', '200ml/7fl oz milk', '2–3 tbsp white wine (optional)', '150ml/3fl oz double cream', '150g/5oz piece thickly carved ham, cut into 2cm/1in chunks', 'sea salt flakes and freshly ground black pepper', '350g/12oz plain flour', '200g/7oz butter', '1 free-range egg, beaten with 1 tbsp cold water, plus 1 egg, beaten, to glaze'],
    method: ['Heat the chicken stock in a lidded saucepan. Add the chicken breast and bring to a low simmer. Cover with a lid and cook for 10 minutes. Remove the chicken breasts from the water with tongs and place on a plate. Pour the cooking liquor into a large jug.', 'Melt 25g/1oz of the butter in a large, heavy-based saucepan over a low heat. Stir in the leeks and fry gently for 2 minutes, stirring occasionally until just softened. Add the garlic and cook for a further minute. Add the remaining butter and stir in the flour as soon as the butter has melted. Cook for 30 seconds, stirring constantly.', 'Slowly pour the milk into the pan, just a little at a time, stirring well between each adding. Gradually add 250ml/10fl oz of the reserved stock and the wine, if using, stirring until the sauce is smooth and thickened slightly. Bring to a gentle simmer and cook for 3 minutes.', 'Season the mixture, to taste, with salt and pepper. Remove from the heat and stir in the cream. Pour into a large bowl and cover the surface of the sauce with cling film to prevent a skin forming. Set aside to cool.', 'Preheat the oven to 200C/180C Fan/Gas 6. Put a baking tray in the oven to heat.', 'For the pastry, put the flour and butter in a food processor and blend on the pulse setting until the mixture resembles fine breadcrumbs. With the motor running, add the beaten egg and water and blend until the mixture forms a ball. Portion off 250g/10oz of pastry for the lid.', 'Roll the remaining pastry out on a lightly floured surface, turning the pastry frequently until around 5mm/¼in thick and 4cm/1½in larger than the pie dish. Lift the pastry over the rolling pin and place it gently into the pie dish. Press the pastry firmly up the sides, making sure there are no air bubbles. Leave the excess pastry overhanging the sides.', 'Cut the chicken breasts into 3cm/1¼in pieces. Stir the chicken, ham and leeks into the cooled sauce. Pour the chicken filling into the pie dish. Brush the rim of the dish with beaten egg. Roll out the reserved pastry for the lid.', 'Cover the pie with the pastry lid and press the edges together firmly to seal. Trim any excess pastry.', 'Make a small hole in the centre of the pie with the tip of a knife. Glaze the top of the pie with beaten egg. Bake on the preheated tray in the centre of the oven for 35–40 minutes, or until the pie is golden-brown all over and the filling is piping hot.'],
    image: 'https://i.imgur.com/UpYo1jm.jpg',
    category: ['Chicken', 'Comfort food'],
    type: ['Dinner'],
    dietary: [''],
    serves: '6',
    complexity: 'Medium',
    time: '2 hours',
    user: user
  },

  {
    name: 'Pasta Puttanesca',
    author: 'Felicity Cloake',
    about: 'A classic store cupboard pasta staple',
    ingredients: ['160g spaghetti', '3 tbsp good olive oil', '2 garlic cloves, very thinly sliced', '4 anchovies, rinsed if packed in salt, roughly chopped', '½ tsp chilli flakes', '50g good-quality black olives, stoned and roughly chopped', '1 tbsp brined capers, rinsed if packed in salt, roughly chopped', '100ml passata', '2 tbsp tomato puree', 'Small bunch of flat-leaf parsley, roughly chopped'],
    method: ['Put a large pan of well-salted water on to boil. When bubbling, add the pasta, stir, and cook for 8-10 minutes according to packet instructions, until very slightly underdone.', 'Heat the oil in a frying pan over a medium-low heat. Cook the garlic very gently until just beginning to colour, then add the anchovies and stir to dissolve. Stir in the chilli flakes, then the olives and capers, and turn up the heat slightly until you can hear them sizzling.', 'Add the passata and puree and stir well, then simmer vigorously for about five minutes, or until the pasta is done. Check the seasoning.', 'Drain the pasta well, then tip into the frying pan and toss well to combine. Divide between bowls and top with the parsley.'],
    image: 'https://i.imgur.com/Nayu4W2.jpg',
    category: ['Pasta', 'Italian'],
    type: ['Dinner'],
    dietary: [''],
    serves: '2',
    complexity: 'Easy',
    time: '30 minutes',
    user: user
  },

  {
    name: 'Salmon, Fennel & Pea Risotto',
    author: 'Mary Berry',
    about: 'Risotto is such a quick and easy dish: the creamy rice is complemented here by the salmon and peas. Be careful not to overcook it, though, or it will be stodgy.',
    ingredients: ['750ml/1 pint 6fl oz hot fish or vegetable stock', '2 tbsp sunflower oil', '½ fennel bulb (or 1 small bulb), trimmed and finely chopped', '2 garlic cloves, crushed', '225g/8oz arborio or risotto rice', '300ml/10fl oz dry white wine', '150g/5½oz frozen petits pois', '½ lemon, juice only', '2 x 150g/5½oz salmon fillets, skinned and thinly sliced', '3 tbsp full-fat crème fraîche', '3 sprigs fresh tarragon, coarsely chopped', '30g/1oz Parmesan, grated, plus extra for sprinkling', 'salt and freshly ground black pepper', '50g/2oz pea shoots, to ganish'],
    method: ['Pour the stock into a saucepan and keep warm over a low heat.', 'Pour the oil into a large frying pan over a medium-high heat. Add the fennel and fry for about 4 minutes, or until softened, but not browned, stirring often. Add the garlic and rice and fry for a minute, stirring constantly, until the grains of rice are coated in the oil.', 'Pour the wine into the stock, stir and bring to a gentle simmer. Add a ladleful of the hot stock mixture to the rice and simmer, stirring continuously. Wait until the stock is almost fully absorbed before adding the next ladleful. Continue to add the stock, a ladleful at a time, and cook the risotto for 15–20 minutes, or until you are left with about 250ml/9fl oz stock in the saucepan and the rice is nearly cooked.', 'Add the petits pois and lemon juice. Ladle in some of the remaining stock and keep stirring for a couple of minutes. Add the salmon slices, crème fraîche, tarragon and Parmesan. Stir and continue to cook until the salmon is done to your liking.', 'Season to taste with salt and pepper and serve immediately, sprinkled with extra parmesan and garnished with pea shoots.'],
    image: 'https://i.imgur.com/JJGqXhI.jpg',
    category: ['Rice', 'Italian', 'Seafood'],
    type: ['Dinner'],
    dietary: [''],
    serves: '6',
    complexity: 'Easy',
    time: '1 hour',
    user: user
  },

  {
    name: 'Mushroom & Herb Tagliatelle',
    author: 'Rachel Roddy',
    about: 'Earthy, mushroomy, herby comfort. Omit the butter and Parmesan and this dish can be vegan',
    ingredients: ['25g dried porcini', '800g mushrooms, mixed varieties, wild or cultivated', '4 tbsp olive oil', '120g butter', '2 garlic cloves, peeled and finely chopped', 'Salt and black pepper', 'Parsley, oregano and thyme, finely chopped', '450g dried long pasta (ideally pappardelle or tagliatelle)', 'Parmesan, grated'],
    method: ['Soak the porcini in warm water for 30 minutes, then drain, reserving the liquid. Clean the other mushrooms by brushing away any mud and then wiping the cap and stem with a damp cloth. Cut all the cleaned mushrooms into slices; not too thin. Put a large pan of well-salted water on to boil in preparation for cooking the pasta.', 'In a large frying pan, heat the oil and butter. Once the butter is foaming gently, add the garlic and fry for a few minutes. Add the porcini and cook for another minute to combine the flavours. Add the fresh mushrooms. Sprinkle with salt and pepper and cook, stirring occasionally, for 5–6 minutes, or until the mushrooms have released their water and are tender and glistening. Add a little of the porcini liquid and let it all bubble for another minute to reduce, then sprinkle with the herbs.', 'Meanwhile, cook the pasta until al dente. Drain and toss with the mushrooms. Divide between bowls and serve, passing around grated cheese for those who want it.'],
    image: 'https://i.imgur.com/BTDsfqb.jpg',
    category: ['Pasta', 'Italian'],
    type: ['Dinner'],
    dietary: ['Vegetarian', 'Vegan'],
    serves: '4',
    complexity: 'Easy',
    time: '45 minutes',
    user: user
  },

  {
    name: 'Potato al forno',
    author: 'Jamie Oliver',
    about: 'Comforting creamy fennel, onions, garlic and Parmesan. Omit the anchovy and swap the Parmesan for a veggie alternative for vegetarians',
    ingredients: ['1 kg Maris Piper potatoes', '2 onions', '2 bulbs of fennel', '600 ml whole milk', '400 ml double cream', '6 anchovy fillets , in oil', '8 cloves of garlic', '½ a bunch of fresh rosemary , (15g)', '6 fresh bay leaves', '1 whole nutmeg , for grating', '50 g Parmesan cheese'],
    method: ['Peel the potatoes and onions and trim the fennel bulbs, reserving any herby fennel tops for later.', 'Finely slice the potatoes, onions and fennel just under ½cm thick, with patient knife skills or, ideally, on a mandolin (use the guard!).', 'Preheat the oven to 180ºC/350ºF/gas 4', 'Pour the milk and cream into a pan. Tear in the anchovies, crush in the unpeeled garlic through a garlic crusher, add the rosemary sprigs and bay leaves and finely grate in half the nutmeg.', 'Bring to a light boil on a medium heat, then immediately turn the heat off and leave to infuse for a few minutes. Fish out and discard the herbs, finely grate and whisk in most of the Parmesan, then taste and season to perfection.', 'In a 25cm x 30cm baking dish, layer up the slices of potato, onion and fennel. Pour over the cream mixture and finely grate over the remaining Parmesan.', 'Cover with tin foil and bake for 30 minutes, then remove the foil and bake for another 45 minutes, or until tender and nicely golden.', 'Remove from the oven, tear and scatter over any reserved fennel tops, and serve.'],
    image: 'https://i.imgur.com/t3SulYB.jpg',
    category: ['Side', 'Comfort food'],
    type: ['Dinner'],
    dietary: ['Vegetarian'],
    serves: '8-10',
    complexity: 'Easy',
    time: '1 hour and 50 minutes',
    user: user
  },

  {
    name: 'Cauliflower Shawarma',
    author: 'Berber & Q',
    about: 'Rich and exotic spices elevate the humble cauliflower to something exceptional. Swap the butter for olive oil to make this vegan.',
    ingredients: ['1 whole cauliflower, outer leaves trimmed', '40g unsalted butter, softened to room temperature', 'Juice of 1 lemon', '1 garlic clove, minced', '1½ tbsp coriander, finely chopped', '1 tbsp ground cinnamon', '1 tbsp ground sumac', '1½ tsp ground cumin', '½ tsp ground allspice', '1 pinch ground nutmeg', '1 pinch ground cardamom', '100g tahini', '1 tbsp lemon juice (optional)', '1 garlic clove, minced (optional)', '100ml iced water', '1 tbsp pomegranate molasses', '1½ tbsp pine nuts, toasted', '1 small green chilli, finely chopped', '2 tbsp pomegranate seeds', '1 tsp dried rose petals', '1 tbsp flat-leaf parsley, roughly chopped', 'Extra-virgin olive oil (optional)'],
    method: ['Whisk all the butter ingredients well until slightly stiff with no streaks. Set aside until needed – just bring to to room temperature before use.', 'Trim the cauliflower, leaving some leafy remnants behind – they taste delicious and look great when burnt and crisped. Parboil in salted water for seven minutes or so, until tender to a knife, but al dente. Set aside to dry, then brush liberally with the spiced butter – retain some of the butter for brushing later – and season well.', 'Heat the oven to 240C/465F/gas 9) and roast for up to seven minutes, until lightly charred all over, then finish on the barbecue for a few minutes for a final hit of smokiness, basting it periodically with any leftover butter.', 'Mix the tahini with the lemon juice and garlic (if using).in a bowl, gradually whisk in the iced water to a thick sauce with the consistency of honey, then season to taste. Alternatively, you can blitz the tahini in a food processor or whisk together using a stand mixer, adding the water gradually to combine.', 'To serve, transfer the whole cauliflower to a serving plate, spoon over the tahini sauce and pomegranate molasses, then finish by sprinkling with the pine nuts, green chilli, pomegranate seeds, rose petals, parsley and oil.'],
    image: 'https://i.imgur.com/JVqx3mb.jpg',
    category: ['Middle-Eastern'],
    type: ['Dinner'],
    dietary: ['Vegetarian', 'Vegan'],
    serves: '2-4',
    complexity: 'Medium',
    time: '45 minutes',
    user: user
  },

  {
    name: 'Tomato Soup',
    author: 'Felicity Cloake',
    about: 'It is portable, filling, and equally good hot or cold',
    ingredients: ['1kg ripe tomatoes', '4 tbsp olive oil', 'Pinch of sugar', '1 onion, chopped', '1 carrot, peeled and diced', '2 garlic cloves, finely chopped', 'Small bunch of basil, separated into leaves and stalks', '600ml chicken stock', '1 tbsp balsamic vinegar', '2 tbsp creme fraiche', 'Extra virgin olive oil, to serve'],
    method: ['Preheat the oven to 190C and cut the tomatoes in half horizontally. Arrange, cut-side up, in a baking dish, drizzle with half the oil and season with salt, pepper and a pinch of sugar. Bake for about an hour, until softened and beginning to char around the edges.', 'Heat the remaining oil in a large, heavy-based pan over a medium heat and add the onion, carrot and garlic. Cook, stirring regularly, for about 7 minutes until softened. Meanwhile, chop the basil stalks, and then add to the pan and cook for another minute.', ' Add the tomatoes, plus any juices from the dish, to the pan along with the stock. Stir and bring to the boil, then turn the heat down, cover and leave to simmer for 25 minutes, until all the vegetables are soft. Leave to cool slightly.', 'Use a blender to purée the soup, then stir in the vinegar and creme fraiche, and season to taste. Reheat gently, while you tear the basil leaves into pieces, then serve with these and a drizzle of olive oil on top.'],
    image: 'https://i.imgur.com/P7ipxWc.png',
    category: ['Comfort food', 'Soup'],
    type: ['Lunch', 'Dinner'],
    dietary: ['Vegetarian'],
    serves: '4',
    complexity: 'Easy',
    time: '90 minutes',
    user: user
  }

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    // },

    // {
    //   name: '',
    //   author: '',
    //   about: '',
    //   ingredients: [''],
    //   method: [''],
    //   image: '',
    //   category: [''],
    //   type: [''],
    //   dietary: [''],
    //   serves: '',
    //   complexity: '',
    //   time: '',
    //   user: user
    //}
  ]
}



module.exports = recipeSeed
